/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate statistics for the time window */
        get: operations["GetOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated trace list */
        get: operations["ListTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{span_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single trace by span_id */
        get: operations["GetTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cost metrics time series */
        get: operations["GetCostMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latency metrics time series (avg + P99) */
        get: operations["GetLatencyMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Error count time series */
        get: operations["GetErrorMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/tree/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All spans for a given trace_id (for the tree view) */
        get: operations["GetTraceTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cost and call breakdown grouped by a dimension */
        get: operations["GetBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/top-movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Period-over-period change per dimension value */
        get: operations["GetTopMovers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/errors-by-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bucketed failure counts broken by status (error / timeout / rate_limited) */
        get: operations["GetErrorsByStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow-cost-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workflow-level cost rollup with prior-period delta (Overview treemap)
         * @description Aggregates kind='llm' cost by the feature_name of the kind='workflow' row that roots each trace. Includes the same-sized prior window so the frontend can color tiles by delta. Traces with no workflow span land in the "" bucket (rendered as Unattributed).
         */
        get: operations["GetWorkflowCostTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calls grouped by session_id, sorted by recency */
        get: operations["ListSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calls aggregated by prompt_version label
         * @description Powers the Prompts page. One row per distinct prompt_version (set via sdk.trace(name, fn, { promptVersion }) or ScopeCallConfig.defaultPromptVersion). Untagged calls collapse to the empty-string version bucket.
         */
        get: operations["ListPrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List alert events (back-compat alias for /api/v1/alerts/events)
         * @description Returns recent alert events for the org. Maintained as a stable alias
         *     for older dashboard versions; new clients should use
         *     /api/v1/alerts/events directly. The full alerts surface (rules CRUD,
         *     events feed, evaluator) lives under /api/v1/alerts/rules and
         *     /api/v1/alerts/events — see those operations for the current shape.
         */
        get: operations["ListAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Bad Request */
            title: string;
            /** @example 400 */
            status: number;
            /** @example parameter 'from' must be an absolute ISO8601 timestamp */
            detail: string;
        };
        OverviewResponse: {
            total_calls: number;
            /** Format: double */
            total_cost_usd: number;
            /**
             * Format: double
             * @description Subset of total_cost_usd attributable to calls with status != 'success'.
             *     Typically zero (most error paths in the SDKs auto-emit input_tokens=0).
             *     Non-zero values usually indicate mid-stream provider failures where
             *     the provider already processed the prompt before the connection died.
             */
            error_cost_usd: number;
            /** Format: double */
            avg_latency_ms: number;
            /** Format: double */
            p99_latency_ms: number;
            /**
             * Format: double
             * @description 0–100
             */
            error_rate_pct: number;
            unique_traces: number;
        };
        Trace: {
            org_id: string;
            trace_id: string;
            span_id: string;
            parent_span_id?: string | null;
            /** Format: date-time */
            timestamp: string;
            model: string;
            provider: string;
            input_tokens: number;
            output_tokens: number;
            /** Format: double */
            cost_usd: number;
            /**
             * Format: double
             * @description Cost attributed to input tokens (computed at ingest from per-model pricing). Optional — only populated on endpoints whose backend has been updated; legacy responses may omit it.
             */
            input_cost_usd?: number;
            /**
             * Format: double
             * @description Cost attributed to output tokens. See input_cost_usd.
             */
            output_cost_usd?: number;
            latency_ms: number;
            ttft_ms?: number | null;
            /** @enum {string} */
            status: "success" | "error" | "timeout" | "rate_limited";
            error_message?: string | null;
            /** @description Empty string for viewer role */
            input_text?: string | null;
            /** @description Empty string for viewer role */
            output_text?: string | null;
            feature_name?: string | null;
            user_id?: string | null;
            session_id?: string | null;
            /** @description B2B customer / tenant identifier (distinct from user_id, which is the end-user). Powers per-customer cost attribution. (v0.3) */
            customer_id?: string | null;
            environment: string;
            sdk_version?: string | null;
            extra?: string | null;
            /** @description Operator-supplied prompt iteration label. Set via sdk.trace(name, fn, { promptVersion }) or via ScopeCallConfig.defaultPromptVersion. Powers the Prompts page. */
            prompt_version?: string | null;
            /**
             * @description Span kind. `llm` = an instrumented provider call; the other three are container spans (no model/tokens/cost of their own) that aggregate cost from their LLM descendants. workflow → agent → step is the conventional hierarchy but nesting is not enforced. (v0.3)
             * @enum {string}
             */
            kind?: "llm" | "workflow" | "agent" | "step";
            /** @description 1-based caller-attempt index. Increments only when the application retries (not provider-SDK-internal retries). Default 1. (v0.3) */
            attempt_number?: number;
            /**
             * @description Reason for this retry; null on attempt 1. (v0.3)
             * @enum {string|null}
             */
            retry_reason?: "rate_limit" | "timeout" | "server_error" | "transient_network" | "agent_decision" | "manual" | "unknown" | null;
            /** @description True for non-production traffic (eval, CI, smoke tests, replays, backfills). The dashboard's "Production only" toggle filters by this. (v0.3) */
            is_test?: boolean;
            /**
             * Format: double
             * @description Cost of the cached input-token portion. Server-derived from the pricing table; 0 when the model has no cache_read rate or no cached tokens were read. (v0.3)
             */
            cache_read_cost_usd?: number;
            /**
             * @description Trust signal for cost_usd. server_computed = priced from the pricing table; sdk_fallback = SDK-supplied because the model was unknown; unknown_model = no cost data available; container = synthetic span (workflow / agent / step) that has no model of its own. (v0.3)
             * @enum {string}
             */
            cost_source?: "server_computed" | "sdk_fallback" | "unknown_model" | "container";
            /** @description Pricing-table version that produced cost_usd (YYYY-MM-DD verification date). (v0.3) */
            pricing_version?: string | null;
        };
        TraceListResponse: {
            traces: components["schemas"]["Trace"][];
            /** @description Opaque cursor for the next page. Absent (or null) on the last page. */
            next_cursor?: string | null;
        };
        /** @description Every span belonging to a single trace_id, chronological. The shape of each span mirrors the Trace schema. The frontend builds the tree hierarchy locally from parent_span_id. */
        TraceTreeResponse: {
            spans: components["schemas"]["Trace"][];
        };
        MetricPoint: {
            /** Format: date-time */
            timestamp: string;
            model?: string | null;
            call_count?: number | null;
            /** Format: double */
            total_cost_usd?: number | null;
            /** Format: double */
            avg_latency_ms?: number | null;
            /** Format: double */
            p99_latency_ms?: number | null;
            error_count?: number | null;
        };
        MetricsResponse: {
            points: components["schemas"]["MetricPoint"][];
        };
        BreakdownRow: {
            /** @description The dimension value (e.g. "gpt-4o"). Empty string denotes unattributed calls — rendered as "(none)" in the UI. */
            key: string;
            /** @description Secondary-dimension value. Populated only when secondary_group_by is set. */
            key2?: string;
            calls: number;
            /** Format: double */
            total_cost_usd: number;
            /** Format: double */
            avg_cost_per_call: number;
            error_count: number;
            /**
             * Format: double
             * @description This group's share of total cost across all groups in the window (0–100).
             */
            pct_of_total: number;
        };
        BreakdownResponse: {
            group_by: string;
            /** @description Echoed when cross-dim mode was requested. */
            secondary_group_by?: string;
            rows: components["schemas"]["BreakdownRow"][];
            /**
             * Format: double
             * @description Total cost across all groups in the window (not just the returned rows).
             */
            total_cost_usd: number;
            total_calls: number;
        };
        TopMoverRow: {
            key: string;
            /** Format: double */
            current_cost_usd: number;
            /** Format: double */
            prior_cost_usd: number;
            /** Format: double */
            delta_cost_usd: number;
            /**
             * Format: double
             * @description Percent change vs prior period (0–N). Sentinel value `-1` means no prior baseline (new dimension value this window) — retained for backward compatibility. New clients should check `is_new` instead.
             */
            pct_change: number;
            /** @description True when this dimension value has no prior-period baseline (first time seen in this window). Distinct from a real -1% delta. */
            is_new?: boolean;
            current_calls: number;
            prior_calls: number;
            /** Format: double */
            current_p99_ms: number;
            /** Format: double */
            prior_p99_ms: number;
            /** Format: double */
            delta_p99_ms: number;
        };
        TopMoversResponse: {
            group_by: string;
            window_seconds: number;
            rows: components["schemas"]["TopMoverRow"][];
        };
        WorkflowCostNode: {
            /** @description Workflow feature_name. Empty string when LLM calls were emitted without an enclosing sdk.workflow() block — the dashboard renders this bucket as "Unattributed". */
            name: string;
            /** Format: double */
            current_cost_usd: number;
            /** Format: double */
            prior_cost_usd: number;
            /** Format: double */
            delta_cost_usd: number;
            /**
             * Format: double
             * @description Same -1 sentinel convention as TopMoverRow: -1 = no prior baseline (use is_new instead).
             */
            pct_change: number;
            is_new: boolean;
            current_calls: number;
            error_count: number;
            /** @description Distinct non-empty customer_id values in the current window. */
            customer_count: number;
            /**
             * Format: double
             * @description Fraction of current-window LLM rows with is_test=true (0..1).
             */
            is_test_share: number;
        };
        WorkflowCostTreeResponse: {
            window_seconds: number;
            /**
             * Format: double
             * @description Sum of current_cost_usd across all returned workflows.
             */
            total_cost_usd: number;
            workflows: components["schemas"]["WorkflowCostNode"][];
        };
        ErrorBucket: {
            /** Format: date-time */
            timestamp: string;
            error: number;
            timeout: number;
            rate_limited: number;
        };
        ErrorsByStatusResponse: {
            points: components["schemas"]["ErrorBucket"][];
        };
        Session: {
            session_id: string;
            /** @description Any non-null user_id seen in the session; empty if all calls were unattributed. */
            user_id?: string;
            call_count: number;
            /** Format: double */
            total_cost_usd: number;
            error_count: number;
            /** Format: date-time */
            first_at: string;
            /** Format: date-time */
            last_at: string;
            /** @description last_at − first_at in milliseconds. */
            duration_ms: number;
        };
        SessionsResponse: {
            sessions: components["schemas"]["Session"][];
        };
        PromptRow: {
            /** @description Prompt version label. Empty string = untagged bucket. */
            version: string;
            calls: number;
            total_cost_usd: number;
            avg_cost_per_call: number;
            p50_latency_ms: number;
            p95_latency_ms: number;
            avg_input_tokens: number;
            avg_output_tokens: number;
            error_count: number;
            error_rate: number;
            /** Format: date-time */
            first_seen: string;
            /** Format: date-time */
            last_seen: string;
        };
        PromptsResponse: {
            rows: components["schemas"]["PromptRow"][];
        };
        AlertListResponse: {
            alerts: unknown[];
            message: string;
        };
    };
    responses: {
        /** @description Bad request */
        Problem400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unauthorized */
        Problem401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Forbidden */
        Problem403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found */
        Problem404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Organization ID. Must match the org_id in the authenticated token. */
        OrgId: string;
        /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
        From: string;
        /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
        To: string;
        Granularity: "hour" | "day";
        /** @description Dimension to aggregate cost and calls by. model/provider/feature read the pre-aggregated hourly rollup; user/environment scan raw calls over the window. */
        GroupBy: "model" | "provider" | "feature" | "user" | "environment";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetOverview: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    ListTraces: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Opaque cursor from previous response's next_cursor field */
                cursor?: string;
                limit?: number;
                model?: string;
                status?: "success" | "error" | "timeout" | "rate_limited";
                feature_name?: string;
                provider?: string;
                user_id?: string;
                environment?: string;
                /** @description Filter to one prompt version (set via sdk.trace(..., {promptVersion}) or ScopeCallConfig.defaultPromptVersion). Pass __null__ to show untagged calls only — matches the Prompts page's "(untagged)" row. */
                prompt_version?: string;
                /** @description v0.3 — B2B tenant filter. Drilled into from /dashboard/customers and the workflow-detail by-customer panel. Pass __null__ to show calls with no customer_id (the "Unattributed" tile on the Customers page). */
                customer_id?: string;
                /** @description Free-text search. Exact-match on span_id / trace_id / session_id / user_id; case-insensitive substring on input_text / output_text / error_message (text-column matching skipped for viewer role). */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace list with optional next_cursor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    GetTrace: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
            };
            header?: never;
            path: {
                span_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"];
                };
            };
            401: components["responses"]["Problem401"];
            404: components["responses"]["Problem404"];
        };
    };
    GetCostMetrics: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost metric points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
        };
    };
    GetLatencyMetrics: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latency metric points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
        };
    };
    GetErrorMetrics: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Error metric points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
        };
    };
    GetTraceTree: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Optional time window hint. When provided alongside `to`, narrows the ClickHouse partition scan to that window. Skipping this triggers a cheap min/max probe to bound the scan automatically. Pass the date range the user was on when they navigated to this trace. */
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All spans for the trace, ordered by timestamp ascending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceTreeResponse"];
                };
            };
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
        };
    };
    GetBreakdown: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Dimension to aggregate cost and calls by. model/provider/feature read the pre-aggregated hourly rollup; user/environment scan raw calls over the window. */
                group_by?: components["parameters"]["GroupBy"];
                /** @description When set, cross-dimensional mode — returns one row per (group_by × secondary_group_by) combination. Always reads raw llm_calls (rollup lacks user/env columns). */
                secondary_group_by?: "model" | "provider" | "feature" | "user" | "environment";
                /** @description Max groups to return (sorted by cost descending). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Breakdown rows sorted by cost descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    GetTopMovers: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Dimension to aggregate cost and calls by. model/provider/feature read the pre-aggregated hourly rollup; user/environment scan raw calls over the window. */
                group_by?: components["parameters"]["GroupBy"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dimension values ordered by absolute cost delta descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMoversResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    GetErrorsByStatus: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-hour failure breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorsByStatusResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    GetWorkflowCostTree: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflows ordered by current-window cost descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowCostTreeResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    ListSessions: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Scope to a single end-user. Equivalent to a server-side filter. */
                user_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    ListPrompts: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Scope to one feature's prompt versions only. */
                feature_name?: string;
                /** @description Scope to one environment. */
                environment?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prompt-version aggregates sorted by cost descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    ListAlerts: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert event list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            401: components["responses"]["Problem401"];
        };
    };
}
