/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate statistics for the time window */
        get: operations["GetOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated trace list */
        get: operations["ListTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{span_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single trace by span_id */
        get: operations["GetTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cost metrics time series */
        get: operations["GetCostMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latency metrics time series (avg + P99) */
        get: operations["GetLatencyMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Error count time series */
        get: operations["GetErrorMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/tree/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All spans for a given trace_id (for the tree view) */
        get: operations["GetTraceTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cost and call breakdown grouped by a dimension */
        get: operations["GetBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/top-movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Period-over-period change per dimension value */
        get: operations["GetTopMovers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/errors-by-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bucketed failure counts broken by status (error / timeout / rate_limited) */
        get: operations["GetErrorsByStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calls grouped by session_id, sorted by recency */
        get: operations["ListSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calls aggregated by prompt_version label
         * @description Powers the Prompts page. One row per distinct prompt_version (set via sdk.trace(name, fn, { promptVersion }) or ScopeCallConfig.defaultPromptVersion). Untagged calls collapse to the empty-string version bucket.
         */
        get: operations["ListPrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alerts (stub — anomaly detection is not yet implemented) */
        get: operations["ListAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Bad Request */
            title: string;
            /** @example 400 */
            status: number;
            /** @example parameter 'from' must be an absolute ISO8601 timestamp */
            detail: string;
        };
        OverviewResponse: {
            total_calls: number;
            /** Format: double */
            total_cost_usd: number;
            /** Format: double */
            avg_latency_ms: number;
            /** Format: double */
            p99_latency_ms: number;
            /**
             * Format: double
             * @description 0–100
             */
            error_rate_pct: number;
            unique_traces: number;
        };
        Trace: {
            org_id: string;
            trace_id: string;
            span_id: string;
            parent_span_id?: string | null;
            /** Format: date-time */
            timestamp: string;
            model: string;
            provider: string;
            input_tokens: number;
            output_tokens: number;
            /** Format: double */
            cost_usd: number;
            /**
             * Format: double
             * @description Cost attributed to input tokens (computed at ingest from per-model pricing). Optional — only populated on endpoints whose backend has been updated; legacy responses may omit it.
             */
            input_cost_usd?: number;
            /**
             * Format: double
             * @description Cost attributed to output tokens. See input_cost_usd.
             */
            output_cost_usd?: number;
            latency_ms: number;
            ttft_ms?: number | null;
            /** @enum {string} */
            status: "success" | "error" | "timeout" | "rate_limited";
            error_message?: string | null;
            /** @description Empty string for viewer role */
            input_text?: string | null;
            /** @description Empty string for viewer role */
            output_text?: string | null;
            feature_name?: string | null;
            user_id?: string | null;
            session_id?: string | null;
            environment: string;
            sdk_version?: string | null;
            extra?: string | null;
            /** @description Operator-supplied prompt iteration label. Set via sdk.trace(name, fn, { promptVersion }) or via ScopeCallConfig.defaultPromptVersion. Powers the Prompts page. */
            prompt_version?: string | null;
            /**
             * @description Span discriminator. `llm` is an instrumented provider call (the default). `workflow` is the synthetic span emitted by sdk.trace() so the trace tree has a real parent row. Workflow rows have empty model/provider, zero tokens, zero cost — see schemas/clickhouse/004_span_kind.sql.
             * @enum {string}
             */
            kind?: "llm" | "workflow";
        };
        TraceListResponse: {
            traces: components["schemas"]["Trace"][];
            /** @description Opaque cursor for the next page. Absent (or null) on the last page. */
            next_cursor?: string | null;
        };
        /** @description Every span belonging to a single trace_id, chronological. The shape of each span mirrors the Trace schema. The frontend builds the tree hierarchy locally from parent_span_id. */
        TraceTreeResponse: {
            spans: components["schemas"]["Trace"][];
        };
        MetricPoint: {
            /** Format: date-time */
            timestamp: string;
            model?: string | null;
            call_count?: number | null;
            /** Format: double */
            total_cost_usd?: number | null;
            /** Format: double */
            avg_latency_ms?: number | null;
            /** Format: double */
            p99_latency_ms?: number | null;
            error_count?: number | null;
        };
        MetricsResponse: {
            points: components["schemas"]["MetricPoint"][];
        };
        BreakdownRow: {
            /** @description The dimension value (e.g. "gpt-4o"). Empty string denotes unattributed calls — rendered as "(none)" in the UI. */
            key: string;
            /** @description Secondary-dimension value. Populated only when secondary_group_by is set. */
            key2?: string;
            calls: number;
            /** Format: double */
            total_cost_usd: number;
            /** Format: double */
            avg_cost_per_call: number;
            error_count: number;
            /**
             * Format: double
             * @description This group's share of total cost across all groups in the window (0–100).
             */
            pct_of_total: number;
        };
        BreakdownResponse: {
            group_by: string;
            /** @description Echoed when cross-dim mode was requested. */
            secondary_group_by?: string;
            rows: components["schemas"]["BreakdownRow"][];
            /**
             * Format: double
             * @description Total cost across all groups in the window (not just the returned rows).
             */
            total_cost_usd: number;
            total_calls: number;
        };
        TopMoverRow: {
            key: string;
            /** Format: double */
            current_cost_usd: number;
            /** Format: double */
            prior_cost_usd: number;
            /** Format: double */
            delta_cost_usd: number;
            /**
             * Format: double
             * @description Percent change vs prior period (0–N). Sentinel value `-1` means no prior baseline (new dimension value this window) — retained for backward compatibility. New clients should check `is_new` instead.
             */
            pct_change: number;
            /** @description True when this dimension value has no prior-period baseline (first time seen in this window). Distinct from a real -1% delta. */
            is_new?: boolean;
            current_calls: number;
            prior_calls: number;
            /** Format: double */
            current_p99_ms: number;
            /** Format: double */
            prior_p99_ms: number;
            /** Format: double */
            delta_p99_ms: number;
        };
        TopMoversResponse: {
            group_by: string;
            window_seconds: number;
            rows: components["schemas"]["TopMoverRow"][];
        };
        ErrorBucket: {
            /** Format: date-time */
            timestamp: string;
            error: number;
            timeout: number;
            rate_limited: number;
        };
        ErrorsByStatusResponse: {
            points: components["schemas"]["ErrorBucket"][];
        };
        Session: {
            session_id: string;
            /** @description Any non-null user_id seen in the session; empty if all calls were unattributed. */
            user_id?: string;
            call_count: number;
            /** Format: double */
            total_cost_usd: number;
            error_count: number;
            /** Format: date-time */
            first_at: string;
            /** Format: date-time */
            last_at: string;
            /** @description last_at − first_at in milliseconds. */
            duration_ms: number;
        };
        SessionsResponse: {
            sessions: components["schemas"]["Session"][];
        };
        PromptRow: {
            /** @description Prompt version label. Empty string = untagged bucket. */
            version: string;
            calls: number;
            total_cost_usd: number;
            avg_cost_per_call: number;
            p50_latency_ms: number;
            p95_latency_ms: number;
            avg_input_tokens: number;
            avg_output_tokens: number;
            error_count: number;
            error_rate: number;
            /** Format: date-time */
            first_seen: string;
            /** Format: date-time */
            last_seen: string;
        };
        PromptsResponse: {
            rows: components["schemas"]["PromptRow"][];
        };
        AlertListResponse: {
            alerts: unknown[];
            message: string;
        };
    };
    responses: {
        /** @description Bad request */
        Problem400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unauthorized */
        Problem401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Forbidden */
        Problem403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found */
        Problem404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Organization ID. Must match the org_id in the authenticated token. */
        OrgId: string;
        /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
        From: string;
        /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
        To: string;
        Granularity: "hour" | "day";
        /** @description Dimension to aggregate cost and calls by. model/provider/feature read the pre-aggregated hourly rollup; user/environment scan raw calls over the window. */
        GroupBy: "model" | "provider" | "feature" | "user" | "environment";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetOverview: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    ListTraces: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Opaque cursor from previous response's next_cursor field */
                cursor?: string;
                limit?: number;
                model?: string;
                status?: "success" | "error" | "timeout" | "rate_limited";
                feature_name?: string;
                provider?: string;
                user_id?: string;
                environment?: string;
                /** @description Filter to one prompt version (set via sdk.trace(..., {promptVersion}) or ScopeCallConfig.defaultPromptVersion). Pass __null__ to show untagged calls only — matches the Prompts page's "(untagged)" row. */
                prompt_version?: string;
                /** @description Free-text search. Exact-match on span_id / trace_id / session_id / user_id; case-insensitive substring on input_text / output_text / error_message (text-column matching skipped for viewer role). */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace list with optional next_cursor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    GetTrace: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
            };
            header?: never;
            path: {
                span_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trace detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"];
                };
            };
            401: components["responses"]["Problem401"];
            404: components["responses"]["Problem404"];
        };
    };
    GetCostMetrics: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost metric points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
        };
    };
    GetLatencyMetrics: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latency metric points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
        };
    };
    GetErrorMetrics: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Error metric points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
        };
    };
    GetTraceTree: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Optional time window hint. When provided alongside `to`, narrows the ClickHouse partition scan to that window. Skipping this triggers a cheap min/max probe to bound the scan automatically. Pass the date range the user was on when they navigated to this trace. */
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All spans for the trace, ordered by timestamp ascending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceTreeResponse"];
                };
            };
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
        };
    };
    GetBreakdown: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Dimension to aggregate cost and calls by. model/provider/feature read the pre-aggregated hourly rollup; user/environment scan raw calls over the window. */
                group_by?: components["parameters"]["GroupBy"];
                /** @description When set, cross-dimensional mode — returns one row per (group_by × secondary_group_by) combination. Always reads raw llm_calls (rollup lacks user/env columns). */
                secondary_group_by?: "model" | "provider" | "feature" | "user" | "environment";
                /** @description Max groups to return (sorted by cost descending). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Breakdown rows sorted by cost descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    GetTopMovers: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Dimension to aggregate cost and calls by. model/provider/feature read the pre-aggregated hourly rollup; user/environment scan raw calls over the window. */
                group_by?: components["parameters"]["GroupBy"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dimension values ordered by absolute cost delta descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMoversResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    GetErrorsByStatus: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-hour failure breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorsByStatusResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    ListSessions: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Scope to a single end-user. Equivalent to a server-side filter. */
                user_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    ListPrompts: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-01T00:00:00Z). Relative values (now-24h) are rejected with 400. */
                from: components["parameters"]["From"];
                /** @description Absolute ISO8601 timestamp (e.g. 2026-05-22T00:00:00Z). Must be after 'from'. */
                to: components["parameters"]["To"];
                /** @description Scope to one feature's prompt versions only. */
                feature_name?: string;
                /** @description Scope to one environment. */
                environment?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prompt-version aggregates sorted by cost descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptsResponse"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
        };
    };
    ListAlerts: {
        parameters: {
            query: {
                /** @description Organization ID. Must match the org_id in the authenticated token. */
                org_id: components["parameters"]["OrgId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert list (currently always empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            401: components["responses"]["Problem401"];
        };
    };
}
