// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, org_id, key_hash, key_prefix, name, scopes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, key_prefix, scopes, revoked, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID        string         `json:"id"`
	OrgID     string         `json:"org_id"`
	KeyHash   string         `json:"key_hash"`
	KeyPrefix sql.NullString `json:"key_prefix"`
	Name      sql.NullString `json:"name"`
	Scopes    []string       `json:"scopes"`
}

type CreateAPIKeyRow struct {
	ID         string         `json:"id"`
	OrgID      string         `json:"org_id"`
	Name       sql.NullString `json:"name"`
	KeyPrefix  sql.NullString `json:"key_prefix"`
	Scopes     []string       `json:"scopes"`
	Revoked    bool           `json:"revoked"`
	CreatedAt  time.Time      `json:"created_at"`
	LastUsedAt sql.NullTime   `json:"last_used_at"`
	RevokedAt  sql.NullTime   `json:"revoked_at"`
}

// Insert a new key. The raw token is generated and hashed by the caller —
// this query only sees the hash + the public prefix. RETURNING gives us the
// generated id + created_at so the API response is correct without a second
// round trip. scopes is NOT NULL on create (the handler always passes the
// requested scope set; never the legacy NULL "all-scopes" sentinel).
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.OrgID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Name,
		pq.Array(arg.Scopes),
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.KeyPrefix,
		pq.Array(&i.Scopes),
		&i.Revoked,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteOldRevokedAPIKeys = `-- name: DeleteOldRevokedAPIKeys :execrows
DELETE FROM api_keys
WHERE revoked = TRUE
  AND revoked_at IS NOT NULL
  AND revoked_at < $1
`

// Permanently delete revoked keys older than the retention window.
// Filters on revoked_at IS NOT NULL so legacy pre-migration revoked rows
// (with a NULL revoked_at) are never auto-cleaned — operators must clean
// those by hand if they want.
//
// $1 is the retention cutoff timestamp (i.e. NOW() - INTERVAL 'N days');
// the cutoff is computed in Go so the goroutine config knob applies
// cleanly without a sqlc-side parameter type for INTERVAL.
func (q *Queries) DeleteOldRevokedAPIKeys(ctx context.Context, revokedAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldRevokedAPIKeys, revokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAPIKeys = `-- name: ListAPIKeys :many

SELECT id, org_id, name, key_prefix, scopes, revoked, created_at, last_used_at, revoked_at
FROM api_keys
WHERE org_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         string         `json:"id"`
	OrgID      string         `json:"org_id"`
	Name       sql.NullString `json:"name"`
	KeyPrefix  sql.NullString `json:"key_prefix"`
	Scopes     []string       `json:"scopes"`
	Revoked    bool           `json:"revoked"`
	CreatedAt  time.Time      `json:"created_at"`
	LastUsedAt sql.NullTime   `json:"last_used_at"`
	RevokedAt  sql.NullTime   `json:"revoked_at"`
}

// api_keys.sql — sqlc queries for the dashboard's key management UI.
//
// Auth middleware uses GetActiveAPIKey (in auth.sql) on every request, so we
// deliberately keep these listing/admin queries out of the hot path: they're
// only called from the settings page or the periodic cleanup goroutine.
// Returns every key for an org, newest first. Includes revoked keys so the
// dashboard's Revoked tab can show audit history (with an auto-delete
// countdown derived from revoked_at).
func (q *Queries) ListAPIKeys(ctx context.Context, orgID string) ([]ListAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.KeyPrefix,
			pq.Array(&i.Scopes),
			&i.Revoked,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked    = TRUE,
    revoked_at = NOW()
WHERE id = $1 AND org_id = $2 AND revoked = FALSE
RETURNING key_hash
`

type RevokeAPIKeyParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

// Soft-delete: flip the revoked flag AND stamp revoked_at. The cleanup
// goroutine uses revoked_at (not created_at) to decide what's old enough to
// permanently delete, so a key minted a year ago and revoked today gets the
// full retention window starting now. Returns key_hash so the handler can
// DEL key:<hash> from Redis for immediate revocation (Round-7 review).
// Scoped by org_id so cross-org guessing can't revoke another tenant's keys.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, revokeAPIKey, arg.ID, arg.OrgID)
	var key_hash string
	err := row.Scan(&key_hash)
	return key_hash, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < NOW() - INTERVAL '60 seconds')
`

// Bumps last_used_at to now() if the row's previous stamp is older than the
// coalesce-window (60s). Auth middleware calls this opportunistically — it's
// a write on the hot path, but coalescing keeps the write rate bounded
// regardless of request rate.
func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAPIKeyLastUsed, id)
	return err
}
