// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const getActiveAPIKey = `-- name: GetActiveAPIKey :one
SELECT org_id, id AS key_id, scopes
FROM api_keys
WHERE key_hash = $1
  AND revoked = false
LIMIT 1
`

type GetActiveAPIKeyRow struct {
	OrgID  string   `json:"org_id"`
	KeyID  string   `json:"key_id"`
	Scopes []string `json:"scopes"`
}

// Hot-path lookup used by the Go API auth middleware on every Bearer-
// token request. Returns the org_id, the key's id (so we can bump
// last_used_at), and the key's scopes (so the middleware can gate the
// request on traces:read for read endpoints).
func (q *Queries) GetActiveAPIKey(ctx context.Context, keyHash string) (GetActiveAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveAPIKey, keyHash)
	var i GetActiveAPIKeyRow
	err := row.Scan(&i.OrgID, &i.KeyID, pq.Array(&i.Scopes))
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, created_at
FROM orgs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrgByID(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRowContext(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
