// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AlertEvent struct {
	ID         string       `json:"id"`
	RuleID     string       `json:"rule_id"`
	FiredAt    time.Time    `json:"fired_at"`
	Value      float64      `json:"value"`
	Message    string       `json:"message"`
	ResolvedAt sql.NullTime `json:"resolved_at"`
}

type AlertRule struct {
	ID            string          `json:"id"`
	OrgID         string          `json:"org_id"`
	Name          string          `json:"name"`
	Type          string          `json:"type"`
	Threshold     float64         `json:"threshold"`
	WindowSeconds int32           `json:"window_seconds"`
	DimFilter     json.RawMessage `json:"dim_filter"`
	ChannelType   string          `json:"channel_type"`
	ChannelConfig json.RawMessage `json:"channel_config"`
	Enabled       bool            `json:"enabled"`
	CreatedAt     time.Time       `json:"created_at"`
}

type ApiKey struct {
	ID         string         `json:"id"`
	OrgID      string         `json:"org_id"`
	KeyHash    string         `json:"key_hash"`
	Name       sql.NullString `json:"name"`
	Revoked    bool           `json:"revoked"`
	CreatedAt  time.Time      `json:"created_at"`
	KeyPrefix  sql.NullString `json:"key_prefix"`
	LastUsedAt sql.NullTime   `json:"last_used_at"`
	Scopes     []string       `json:"scopes"`
	RevokedAt  sql.NullTime   `json:"revoked_at"`
}

type Org struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type SavedView struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	CreatedBy   sql.NullString `json:"created_by"`
	Name        string         `json:"name"`
	Path        string         `json:"path"`
	QueryString string         `json:"query_string"`
	Icon        sql.NullString `json:"icon"`
	CreatedAt   time.Time      `json:"created_at"`
}
